### ISSUE TITLE
Plugin Development Instructions

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/bloodmoon#1]
This is a minigame-like plugin, hooks with [InfernalMobs](http://dev.bukkit.org/bukkit-plugins/infernal-mobs/).
### Configuration files
- `config.yml`
  - language
  - call timeout ticks
  - preparation time ticks
  - enable pvp (`true` or `false`)
  - save inventory (`none` or `chest`)
  - config automatically update with new attribute in plugin
- `arena.yml`
  - stores all arena data
- `level.yml`
  - stores all difficulty definitions
- `mob.yml`
  - stores all pre-defined mobs
- `reward.yml`
  - winner kits definitions
  - general bonus for killing every mob (including normal and infernal, added to user account realtime)
    - e.g., killing a normal mob gets $1.
  - general leveled bonus for killing/assist killing every infernal mobs
    - e.g., killing a level 1 infernal gets $10, all players assist killing get $5. Killing a level 2 infernal gets $15, all players assist killing get $10.
- `stats.yml`
  - Stores all player stats for infernal kill / normal kill / assist / death / events joined / wining times
  - This file only stores overall stats
  - Can be shown top stats on signs?
- language file, e.g., `lang/en_US.yml` and `lang/zh_CN.yml`
  - supports color code and `&` escapes
  - automatically update file with new phrases in plugin
### Admin commands
- `/bloodmoon arena [name] [radius] [spawn radius]` or `/bm arena new [radius] [spawn radius]`
  - define/updates a new arena
  - player position as center point
  - `name` as identifier
  - `radius` as max arena area
  - mobs will spawn **outside** `spawn radius` so this value must be smaller than `radius`
- `/bm difficulty [level] [min player amount] [mob:player amount] [mob:infernal amount] [mob spawn delay ticks] [max infernal level]`
  - define/updates a difficulty level
  - `level` is a string identifier, such as `EASY`, `NORMAL`, `HARD`, `INSANE`
  - `min player amount` the minimum required player joining the game
  - `mob:player amount` decides how many mobs will spawn at once based on players amount. Set to 10 and 10 players join the game, will result in 10 x 10 = 100 mobs on every spawn.
  - `mob:infernal amount` decides how many infernal mobs based on every mob spawn. Set to 10 then 1 one out of 10 mobs will be infernal.
  - `mob spawn delay ticks` defines the cooldown time of mob spawn
  - `max infernal level` for every mob spawn event, infernal mobs level will goes up 1 step in `mob.yml`. So this value also defines how many times mobs will spawn.
- `/bm kit [name] [type]`
  - define/updates the winner kits, issue the command and right click on a chest containing all included items to save.
  - `name` is the string identifier
  - `type` includes
    - `mostkill` for infernal kills
    - `mostassist` for infernal assists
    - `mostnormalkill` for normal mob kills
    - `mvp` extra bonus for best warrior in every battle
- `/bm start [arena name] [difficulty level] [kit name]`
  - starts a blood moon event
- `/bm stop [arena name]`
  - stops a blood moon event
### Player commands
- `/bm join` or `/bm in` to respond the call
- `/bm quit`, `/bm fail` or `/bm surrender` to quit the game

Every player join or quit the game, mob and infernal spawn amount should be re-calculated.
### Configuration examples

`mob.yml` Predefined mobs

```
levels:
  '1':
    '1':
      mobtype: zombie
      skills:
      - 1up
    '2':
      mobtype: zombie
      skills:
      - sprint
      - 1up
    '3':
      mobtype: skeleton
      skills:
      - potions
  '2':
    '1':
      mobtype: skeleton
      skills:
      - archer
      - quicksand
    '2':
      mobtype: spider
      skills:
      - sapper
      - lifesteal
...(etc)
```

`reward.yml` bonus rewards

```
normal
  kill: 1  # gives player $1 for every kill of normal mobs

infernal:
  '1':
    kill: 10
    assist: 5
  '2':
    kill: 15
    assist: 10

kits:
    'somekitname':
      mostkill:
        items: (data)
      mostassist:
        items: (data)
      mostnormalkill:
        items: (data)
    'someotherkitname':
      mostkill:
        items: (data)
      mostassist:
        items: (data)
      mostnormalkill:
        items: (data)
```
### Other functions
- On player death, save inventory items in a chest located at death point if `save inventory` set to `chest` and teleport player back to arena center. `save inventory` set to `none` to simply drop all items on ground.
- On every mob kill, calculate killer/assist(if available) and show credits in current battle to all attackers. Credit message example: `You (assist) killed an enemy! Your stats N infernal kills / M normal kills / X assist / Y deaths in current battle.`

(TBD)
### The game
1. When starting a blood moon event, system broadcast call for battle.
2. Player respond to the call. After `call timeout`, if player amount satisfied then start the game, otherwise cancel the game.
3. Broadcast preparation time for battle, as well as the difficulty.
4. Teleport all players to arena center and lock the corresponding world time to 18000 ticks.
5. Countdown preparation time (again) to setup or fix bunker if necessary.
6. Start spawning mobs according to difficulty definition.
7. The game ended with failed message when all players get killed / quit.
8. The game ended with winning message when all mobs cleared.
9. Whether the game win or failed, general normal bonus will be added to player account.
10. If players win the game, calculate `mostkill`, `mostassist` and `mostnormalkill` and send corresponding items to player inventory or ender chest if one player gets two or even 3 of the top, give the player `mostkill` and `mvp` kit items.
11. Broadcast preparation time for teleport back to server spawn point.
